// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: destinations.sql

package db

import (
	"context"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (id, user_id, name, platform, config_nonce, config_enc, key_version, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, platform, config_nonce, config_enc, key_version, enabled, created_at
`

type CreateDestinationParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Platform    string `json:"platform"`
	ConfigNonce []byte `json:"config_nonce"`
	ConfigEnc   []byte `json:"config_enc"`
	KeyVersion  int64  `json:"key_version"`
	Enabled     int64  `json:"enabled"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, createDestination,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Platform,
		arg.ConfigNonce,
		arg.ConfigEnc,
		arg.KeyVersion,
		arg.Enabled,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.ConfigNonce,
		&i.ConfigEnc,
		&i.KeyVersion,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = ? AND user_id = ?
`

type DeleteDestinationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDestination(ctx context.Context, arg DeleteDestinationParams) error {
	_, err := q.db.ExecContext(ctx, deleteDestination, arg.ID, arg.UserID)
	return err
}

const getDestinationByID = `-- name: GetDestinationByID :one
SELECT id, user_id, name, platform, config_nonce, config_enc, key_version, enabled, created_at FROM destinations WHERE id = ? LIMIT 1
`

func (q *Queries) GetDestinationByID(ctx context.Context, id string) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestinationByID, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.ConfigNonce,
		&i.ConfigEnc,
		&i.KeyVersion,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listDestinationsByUser = `-- name: ListDestinationsByUser :many
SELECT id, user_id, name, platform, config_nonce, config_enc, key_version, enabled, created_at FROM destinations WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDestinationsByUser(ctx context.Context, userID string) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listDestinationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.ConfigNonce,
			&i.ConfigEnc,
			&i.KeyVersion,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :exec
UPDATE destinations
SET name = ?, enabled = ?, config_nonce = ?, config_enc = ?, key_version = ?
WHERE id = ? AND user_id = ?
`

type UpdateDestinationParams struct {
	Name        string `json:"name"`
	Enabled     int64  `json:"enabled"`
	ConfigNonce []byte `json:"config_nonce"`
	ConfigEnc   []byte `json:"config_enc"`
	KeyVersion  int64  `json:"key_version"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateDestination,
		arg.Name,
		arg.Enabled,
		arg.ConfigNonce,
		arg.ConfigEnc,
		arg.KeyVersion,
		arg.ID,
		arg.UserID,
	)
	return err
}
