// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: devices.sql

package db

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, name, client_id)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, name, client_id, last_seen_at, created_at
`

type CreateDeviceParams struct {
	ID       string         `json:"id"`
	UserID   string         `json:"user_id"`
	Name     string         `json:"name"`
	ClientID sql.NullString `json:"client_id"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ClientID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, name, client_id, last_seen_at, created_at FROM devices WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByIDAndUser = `-- name: GetDeviceByIDAndUser :one
SELECT id, user_id, name, client_id, last_seen_at, created_at FROM devices WHERE id = ? AND user_id = ? LIMIT 1
`

type GetDeviceByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetDeviceByIDAndUser(ctx context.Context, arg GetDeviceByIDAndUserParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByIDAndUser, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByUserAndClientID = `-- name: GetDeviceByUserAndClientID :one
SELECT id, user_id, name, client_id, last_seen_at, created_at FROM devices WHERE user_id = ? AND client_id = ? LIMIT 1
`

type GetDeviceByUserAndClientIDParams struct {
	UserID   string         `json:"user_id"`
	ClientID sql.NullString `json:"client_id"`
}

func (q *Queries) GetDeviceByUserAndClientID(ctx context.Context, arg GetDeviceByUserAndClientIDParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByUserAndClientID, arg.UserID, arg.ClientID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByUserAndName = `-- name: GetDeviceByUserAndName :one
SELECT id, user_id, name, client_id, last_seen_at, created_at FROM devices WHERE user_id = ? AND name = ? LIMIT 1
`

type GetDeviceByUserAndNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetDeviceByUserAndName(ctx context.Context, arg GetDeviceByUserAndNameParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByUserAndName, arg.UserID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, client_id, last_seen_at, created_at FROM devices WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ClientID,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceClientID = `-- name: UpdateDeviceClientID :exec
UPDATE devices SET client_id = ? WHERE id = ? AND user_id = ?
`

type UpdateDeviceClientIDParams struct {
	ClientID sql.NullString `json:"client_id"`
	ID       string         `json:"id"`
	UserID   string         `json:"user_id"`
}

func (q *Queries) UpdateDeviceClientID(ctx context.Context, arg UpdateDeviceClientIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceClientID, arg.ClientID, arg.ID, arg.UserID)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen_at = ? WHERE id = ?
`

type UpdateDeviceLastSeenParams struct {
	LastSeenAt sql.NullTime `json:"last_seen_at"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastSeen, arg.LastSeenAt, arg.ID)
	return err
}
