// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createForwardLog = `-- name: CreateForwardLog :one
INSERT INTO forward_logs (id, message_id, destination_id, status, error)
VALUES (?, ?, ?, ?, ?)
RETURNING id, message_id, destination_id, status, error, created_at
`

type CreateForwardLogParams struct {
	ID            string         `json:"id"`
	MessageID     string         `json:"message_id"`
	DestinationID string         `json:"destination_id"`
	Status        string         `json:"status"`
	Error         sql.NullString `json:"error"`
}

func (q *Queries) CreateForwardLog(ctx context.Context, arg CreateForwardLogParams) (ForwardLog, error) {
	row := q.db.QueryRowContext(ctx, createForwardLog,
		arg.ID,
		arg.MessageID,
		arg.DestinationID,
		arg.Status,
		arg.Error,
	)
	var i ForwardLog
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.DestinationID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO inbound_messages (
    id, user_id, device_id, client_message_id, sender_nonce, sender_enc, body_nonce, body_enc, key_version, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, device_id, client_message_id, sender_nonce, sender_enc, body_nonce, body_enc, key_version, received_at, created_at
`

type CreateMessageParams struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	DeviceID        sql.NullString `json:"device_id"`
	ClientMessageID sql.NullString `json:"client_message_id"`
	SenderNonce     []byte         `json:"sender_nonce"`
	SenderEnc       []byte         `json:"sender_enc"`
	BodyNonce       []byte         `json:"body_nonce"`
	BodyEnc         []byte         `json:"body_enc"`
	KeyVersion      int64          `json:"key_version"`
	ReceivedAt      time.Time      `json:"received_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (InboundMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.ClientMessageID,
		arg.SenderNonce,
		arg.SenderEnc,
		arg.BodyNonce,
		arg.BodyEnc,
		arg.KeyVersion,
		arg.ReceivedAt,
	)
	var i InboundMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ClientMessageID,
		&i.SenderNonce,
		&i.SenderEnc,
		&i.BodyNonce,
		&i.BodyEnc,
		&i.KeyVersion,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getForwardLogByMessageDestination = `-- name: GetForwardLogByMessageDestination :one
SELECT id, message_id, destination_id, status, error, created_at FROM forward_logs
WHERE message_id = ? AND destination_id = ?
LIMIT 1
`

type GetForwardLogByMessageDestinationParams struct {
	MessageID     string `json:"message_id"`
	DestinationID string `json:"destination_id"`
}

func (q *Queries) GetForwardLogByMessageDestination(ctx context.Context, arg GetForwardLogByMessageDestinationParams) (ForwardLog, error) {
	row := q.db.QueryRowContext(ctx, getForwardLogByMessageDestination, arg.MessageID, arg.DestinationID)
	var i ForwardLog
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.DestinationID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT id, user_id, device_id, client_message_id, sender_nonce, sender_enc, body_nonce, body_enc, key_version, received_at, created_at FROM inbound_messages
WHERE user_id = ? AND device_id = ? AND client_message_id = ?
LIMIT 1
`

type GetMessageByClientIDParams struct {
	UserID          string         `json:"user_id"`
	DeviceID        sql.NullString `json:"device_id"`
	ClientMessageID sql.NullString `json:"client_message_id"`
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (InboundMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByClientID, arg.UserID, arg.DeviceID, arg.ClientMessageID)
	var i InboundMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ClientMessageID,
		&i.SenderNonce,
		&i.SenderEnc,
		&i.BodyNonce,
		&i.BodyEnc,
		&i.KeyVersion,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, user_id, device_id, client_message_id, sender_nonce, sender_enc, body_nonce, body_enc, key_version, received_at, created_at FROM inbound_messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (InboundMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i InboundMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ClientMessageID,
		&i.SenderNonce,
		&i.SenderEnc,
		&i.BodyNonce,
		&i.BodyEnc,
		&i.KeyVersion,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listForwardLogsByMessage = `-- name: ListForwardLogsByMessage :many
SELECT id, message_id, destination_id, status, error, created_at FROM forward_logs WHERE message_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListForwardLogsByMessage(ctx context.Context, messageID string) ([]ForwardLog, error) {
	rows, err := q.db.QueryContext(ctx, listForwardLogsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForwardLog{}
	for rows.Next() {
		var i ForwardLog
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.DestinationID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByUser = `-- name: ListMessagesByUser :many
SELECT id, user_id, device_id, client_message_id, sender_nonce, sender_enc, body_nonce, body_enc, key_version, received_at, created_at FROM inbound_messages
WHERE user_id = ?
ORDER BY received_at DESC
LIMIT ? OFFSET ?
`

type ListMessagesByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMessagesByUser(ctx context.Context, arg ListMessagesByUserParams) ([]InboundMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundMessage{}
	for rows.Next() {
		var i InboundMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.ClientMessageID,
			&i.SenderNonce,
			&i.SenderEnc,
			&i.BodyNonce,
			&i.BodyEnc,
			&i.KeyVersion,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForwardLog = `-- name: UpdateForwardLog :exec
UPDATE forward_logs
SET status = ?, error = ?
WHERE id = ?
`

type UpdateForwardLogParams struct {
	Status string         `json:"status"`
	Error  sql.NullString `json:"error"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateForwardLog(ctx context.Context, arg UpdateForwardLogParams) error {
	_, err := q.db.ExecContext(ctx, updateForwardLog, arg.Status, arg.Error, arg.ID)
	return err
}
