// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Destination struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Name        string    `json:"name"`
	Platform    string    `json:"platform"`
	ConfigNonce []byte    `json:"config_nonce"`
	ConfigEnc   []byte    `json:"config_enc"`
	KeyVersion  int64     `json:"key_version"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
}

type Device struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Name       string         `json:"name"`
	ClientID   sql.NullString `json:"client_id"`
	LastSeenAt sql.NullTime   `json:"last_seen_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type ForwardLog struct {
	ID            string         `json:"id"`
	MessageID     string         `json:"message_id"`
	DestinationID string         `json:"destination_id"`
	Status        string         `json:"status"`
	Error         sql.NullString `json:"error"`
	CreatedAt     time.Time      `json:"created_at"`
}

type InboundMessage struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	DeviceID        sql.NullString `json:"device_id"`
	ClientMessageID sql.NullString `json:"client_message_id"`
	SenderNonce     []byte         `json:"sender_nonce"`
	SenderEnc       []byte         `json:"sender_enc"`
	BodyNonce       []byte         `json:"body_nonce"`
	BodyEnc         []byte         `json:"body_enc"`
	KeyVersion      int64          `json:"key_version"`
	ReceivedAt      time.Time      `json:"received_at"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID                  string    `json:"id"`
	PasswordHash        string    `json:"password_hash"`
	PasswordFingerprint string    `json:"password_fingerprint"`
	CreatedAt           time.Time `json:"created_at"`
}
