// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, password_hash, password_fingerprint)
VALUES (?, ?, ?)
RETURNING id, password_hash, password_fingerprint, created_at
`

type CreateUserParams struct {
	ID                  string `json:"id"`
	PasswordHash        string `json:"password_hash"`
	PasswordFingerprint string `json:"password_fingerprint"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.PasswordHash, arg.PasswordFingerprint)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.PasswordFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByFingerprint = `-- name: GetUserByFingerprint :one
SELECT id, password_hash, password_fingerprint, created_at FROM users WHERE password_fingerprint = ? LIMIT 1
`

func (q *Queries) GetUserByFingerprint(ctx context.Context, passwordFingerprint string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFingerprint, passwordFingerprint)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.PasswordFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, password_hash, password_fingerprint, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.PasswordFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPasswordFingerprint = `-- name: UpdateUserPasswordFingerprint :exec
UPDATE users SET password_fingerprint = ? WHERE id = ?
`

type UpdateUserPasswordFingerprintParams struct {
	PasswordFingerprint string `json:"password_fingerprint"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateUserPasswordFingerprint(ctx context.Context, arg UpdateUserPasswordFingerprintParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordFingerprint, arg.PasswordFingerprint, arg.ID)
	return err
}
